[project]
name = "ai-resume-reviewer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sivanisankar", email = "sivanisankar123@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "openai>=2.53.0",
    "pypdf>=6.15.0",
    "python-dotenv>=1.2.2",
    "streamlit>=1.61.1",
]

[project.scripts]
ai-resume-reviewer = "ai_resume_reviewer:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
